image: node:alpine

test:
  stage: test
  script:
    - node script.js 
  services:
    - name: erikvl87/languagetool
      alias: languagetool


pages:
  stage: deploy
  script:
  - yarn
  - yarn build
  artifacts:
    paths:
    - public
    expire_in: 1 week
  cache:
    paths:
    - node_modules
  only:
  - master
