image: node:10

cache:
  paths:
    - node_modules/

before_script:
  - yarn add gitbook-cli 
  - node node_modules/gitbook-cli/bin/gitbook.js fetch 3.2.3
  - node node_modules/gitbook-cli/bin/gitbook.js install
    
pages:
  stage: deploy
  script:
    - node node_modules/gitbook-cli/bin/gitbook.js build . public
  artifacts:
    paths:
      - public
    expire_in: 1 week
  only:
    - master
