image: node:10

cache:
  paths:
    - node_modules/

before_script:
  - yarn add gitbook-cli 
  - alias gitbook="node node_modules/gitbook-cli/bin/gitbook.js"
  - gitbook fetch 3.2.3
  - gitbook install
    
pages:
  stage: deploy
  script:
    - gitbook build . public
  artifacts:
    paths:
      - public
    expire_in: 1 week
  only:
    - master
