image: node:14.20.1

pages:
  stage: deploy
  script:
  - node build.js > _sidebar.md
  - mkdir .public
  - cp -r * .public
  - mv .public public
  artifacts:
    expire_in: 1 day
    paths:
    - public
  only:
  - master
