image: node:14.8.0

test:
  stage: test
  script:
    - node script.js 
  services:
    - name: erikvl87/languagetool
      alias: languagetool

pages:
  stage: deploy
  script:
  - node build.js > _sidebar.md
  - mkdir .public
  - cp -r * .public
  - mv .public public
  artifacts:
    expire_in: 1 day
    paths:
    - public
  only:
  - master
