image: node

cache:
  paths:
    - node_modules/

before_script:
  - npm install gitbook-cli -g
  - gitbook fetch latest
  - gitbook install
    
pages:
  stage: deploy
  script:
    - gitbook build . public
  artifacts:
    paths:
      - public
    expire_in: 1 week
  only:
    - master
