test:
  image: node:14.8.0
  stage: test
  script:
    - node script.js 
  services:
    - name: erikvl87/languagetool
      alias: languagetool

pages:
  image: node:alpine
  stage: deploy
  script:
  - yarn
  - yarn build
  artifacts:
    paths:
    - public
    expire_in: 1 week
  cache:
    paths:
    - node_modules
  only:
  - master
